import { validateChecklistPayload } from "../../services/checklistService.js";
import { OPTION_GROUP_CHOICES } from "../../services/optionService.js";

const statusOptions = [
  { label: "Ativo", value: "ativo" },
  { label: "Pedir", value: "pedir" },
  { label: "Manutencao", value: "manutencao" },
  { label: "Cancelado", value: "cancelado" },
];

const checklistStatusOptions = [
  { label: "Pendente", value: "pendente" },
  { label: "Rascunho", value: "rascunho" },
  { label: "Finalizado", value: "finalizado" },
  { label: "Abandonado", value: "abandonado" },
];

const proposalStatusOptions = [
  { label: "Aguardando", value: "aguardando" },
  { label: "Concluido", value: "concluido" },
  { label: "Rascunho", value: "rascunho" },
  { label: "Cancelado", value: "cancelado" },
  { label: "Abandonado", value: "abandonado" },
];

const paymentStatusOptions = [
  { label: "Pago", value: "pago" },
  { label: "Pendente", value: "pendente" },
  { label: "Atrasado", value: "atrasado" },
];

const wikiStatusOptions = [
  { label: "Resolvido", value: "resolvido" },
  { label: "Em Andamento", value: "andamento" },
  { label: "Sem Solucao", value: "abandonado" },
];

function resolveName(snapshot, collection, id) {
  return snapshot[collection]?.find((record) => record.id === id)?.name || "-";
}

export const moduleConfigs = {
  machines: {
    title: "Catalogo de Maquinas",
    description: "Gerencie os modelos e equipamentos disponiveis.",
    actionLabel: "Nova Maquina",
    collection: "machines",
    layout: "cards",
    searchPlaceholder: "Buscar por maquina, marca ou categoria",
    formTitle: "Cadastro de Maquina",
    formDescription: "Parametros tecnicos, estoque e precificacao base do equipamento.",
    card: {
      title: { key: "name" },
      subtitle: { key: "brand" },
      statusKey: "status",
      meta: [
        { key: "category", label: "Categoria" },
        { key: "stock", label: "Estoque" },
        { key: "priceRent", label: "Aluguel", type: "currency" },
        { key: "priceSale", label: "Venda", type: "currency" },
      ],
    },
    fields: [
      { name: "name", label: "Nome da maquina", required: true },
      { name: "brand", label: "Marca", type: "select", optionGroup: "Marcas de Maquinas", required: true },
      { name: "category", label: "Categoria", type: "select", optionGroup: "Categorias de Maquinas", required: true },
      { name: "voltage", label: "Voltagem", type: "select", optionGroup: "Voltagens", options: [{ label: "110v", value: "110v" }, { label: "220v", value: "220v" }, { label: "Bivolt", value: "Bivolt" }] },
      { name: "amperage", label: "Amperagem", type: "number", defaultValue: 10 },
      { name: "hydraulic", label: "Rede hidrica", type: "select", optionGroup: "Rede Hidrica", options: [{ label: "Sim", value: "Sim" }, { label: "Nao", value: "Nao" }] },
      { name: "sewer", label: "Esgoto", type: "select", optionGroup: "Rede Hidrica", options: [{ label: "Sim", value: "Sim" }, { label: "Nao", value: "Nao" }], defaultValue: "Nao" },
      { name: "steam", label: "Vapor", type: "select", optionGroup: "Rede Hidrica", options: [{ label: "Sim", value: "Sim" }, { label: "Nao", value: "Nao" }], defaultValue: "Nao" },
      { name: "paymentSystem", label: "Sistema de pagamento", type: "select", optionGroup: "Rede Hidrica", options: [{ label: "Sim", value: "Sim" }, { label: "Nao", value: "Nao" }], defaultValue: "Nao" },
      { name: "paymentSystemName", label: "Qual sistema?" },
      { name: "stock", label: "Estoque", type: "number", defaultValue: 0 },
      { name: "minStock", label: "Estoque minimo", type: "number", defaultValue: 1 },
      { name: "priceRent", label: "Valor aluguel", type: "currency" },
      { name: "priceSale", label: "Valor venda", type: "currency" },
      { name: "status", label: "Status", type: "select", optionGroup: "Status Catalogo", options: statusOptions, defaultValue: "ativo" },
      { name: "description", label: "Descricao", type: "textarea", full: true, maxLength: 800 },
    ],
    extraActions: [
      {
        id: "machineConfigs",
        label: "Config",
        icon: "settings",
        type: "hub",
        hub: {
          collection: "machineConfigs",
          parentKey: "machineId",
          title: (machine) => `Configuracoes - ${machine?.name || ""}`,
          description: () => "Gestao de configuracoes tecnicas e programacao de bebidas.",
          emptyTitle: "Configuracoes salvas",
          actionLabel: "Nova Configuracao",
          formTitle: "Configuracao da Maquina",
          formDescription: "Parametros tecnicos e mapeamento de bebidas do equipamento.",
          columns: [
            { key: "name", label: "Nome" },
            { key: "clientId", label: "Cliente", source: "clients" },
            { key: "drinks", label: "Bebidas" },
            { key: "temperature", label: "Temp." },
          ],
          fields: [
            { name: "name", label: "Nome da configuracao", required: true },
            { name: "clientId", label: "Cliente vinculado", source: "clients" },
            { name: "isDefault", label: "Configuracao padrao", type: "checkbox" },
            { name: "reservoirs", label: "Reservatorios", type: "textarea", full: true },
            { name: "drinks", label: "Bebidas / ML", type: "textarea", full: true },
            { name: "temperature", label: "Temperatura" },
            { name: "grind", label: "Moagem" },
            { name: "notes", label: "Observacoes", type: "textarea", full: true },
          ],
        },
      },
      {
        id: "wikiSolutions",
        label: "Wiki",
        icon: "wrench",
        type: "hub",
        hub: {
          collection: "wikiSolutions",
          parentKey: "machineId",
          title: (machine) => `Wiki - ${machine?.name || ""}`,
          description: () => "Base de conhecimento tecnico e troubleshooting.",
          emptyTitle: "Solucoes catalogadas",
          actionLabel: "Nova Solucao",
          formTitle: "Solucao da Wiki",
          formDescription: "Documente sintomas, evidencias e passo a passo de manutencao.",
          columns: [
            { key: "problem", label: "Problema" },
            { key: "category", label: "Categoria" },
            { key: "difficulty", label: "Dificuldade" },
            { key: "status", label: "Status", type: "status" },
          ],
          fields: [
            { name: "problem", label: "Nome do problema", required: true },
            { name: "category", label: "Categoria", type: "select", optionGroup: "Categorias Wiki", options: [{ label: "Mecanica", value: "Mecanica" }, { label: "Eletrica", value: "Eletrica" }, { label: "Hidraulica", value: "Hidraulica" }, { label: "Configuracao", value: "Configuracao" }] },
            { name: "status", label: "Status", type: "select", optionGroup: "Status Wiki", options: wikiStatusOptions, defaultValue: "andamento" },
            { name: "difficulty", label: "Dificuldade", type: "select", optionGroup: "Dificuldade Wiki", options: [{ label: "Simples", value: "Simples" }, { label: "Media", value: "Media" }, { label: "Dificil", value: "Dificil" }] },
            { name: "tags", label: "Tags de busca" },
            { name: "evidence", label: "Midias e evidencias", type: "textarea", full: true },
            { name: "solution", label: "Passo a passo da solucao", type: "textarea", full: true },
          ],
        },
      },
    ],
  },
  supplies: {
    title: "Catalogo de Insumos",
    description: "Gerenciamento de produtos consumiveis e ingredientes.",
    actionLabel: "Novo Insumo",
    collection: "supplies",
    layout: "cards",
    searchPlaceholder: "Buscar por insumo, marca ou categoria",
    formTitle: "Cadastro de Insumo",
    formDescription: "Dados comerciais, estoque minimo e rendimento para operacao.",
    card: {
      title: { key: "name" },
      subtitle: { key: "brand" },
      statusKey: "status",
      meta: [
        { key: "category", label: "Categoria" },
        { key: "stock", label: "Estoque" },
        { key: "price", label: "Preco", type: "currency" },
        { key: "cost", label: "Custo", type: "currency" },
      ],
    },
    fields: [
      { name: "name", label: "Nome do produto", required: true },
      { name: "brand", label: "Marca", type: "select", optionGroup: "Marcas de Insumos" },
      { name: "category", label: "Categoria", type: "select", optionGroup: "Categorias de Insumos" },
      { name: "unit", label: "Tamanho / medida", type: "select", optionGroup: "Unidades de Produto" },
      { name: "stock", label: "Estoque", type: "number", defaultValue: 0 },
      { name: "minStock", label: "Estoque minimo", type: "number", defaultValue: 1 },
      { name: "price", label: "Preco venda", type: "currency" },
      { name: "cost", label: "Custo", type: "currency" },
      { name: "status", label: "Status", type: "select", optionGroup: "Status Catalogo", options: statusOptions, defaultValue: "ativo" },
      { name: "description", label: "Descricao", type: "textarea", full: true, maxLength: 800 },
    ],
    extraActions: [
      {
        id: "recipes",
        label: "Receitas",
        icon: "receipt",
        type: "hub",
        hub: {
          collection: "recipes",
          parentKey: "supplyId",
          title: (supply) => `Receitas - ${supply?.name || ""}`,
          description: () => "Fichas tecnicas de preparos vinculadas ao insumo.",
          emptyTitle: "Receitas cadastradas",
          actionLabel: "Nova Receita",
          formTitle: "Ficha Tecnica",
          formDescription: "Ingredientes, preparo, alergenicos e custo estimado.",
          columns: [
            { key: "name", label: "Receita" },
            { key: "yield", label: "Rendimento" },
            { key: "allergens", label: "Alergenicos" },
            { key: "cost", label: "Custo", type: "currency" },
          ],
          fields: [
            { name: "name", label: "Nome da receita", required: true },
            { name: "yield", label: "Rendimento" },
            { name: "allergens", label: "Alergenicos / dieta" },
            { name: "ingredients", label: "Ingredientes", type: "textarea", full: true },
            { name: "preparation", label: "Modo de preparo", type: "textarea", full: true },
            { name: "cost", label: "Custo estimado", type: "currency" },
            { name: "notes", label: "Observacoes", type: "textarea", full: true },
          ],
        },
      },
    ],
  },
  accessories: {
    title: "Catalogo de Acessorios",
    description: "Gerenciamento de pecas, moveis e acessorios perifericos.",
    actionLabel: "Novo Acessorio",
    collection: "accessories",
    layout: "cards",
    formTitle: "Cadastro de Acessorio",
    formDescription: "Dados de compatibilidade, estoque e precificacao do acessorio.",
    card: {
      title: { key: "name" },
      subtitle: { key: "brand" },
      statusKey: "status",
      meta: [
        { key: "category", label: "Categoria" },
        { key: "stock", label: "Estoque" },
        { key: "price", label: "Preco", type: "currency" },
        { key: "color", label: "Cor" },
      ],
    },
    fields: [
      { name: "name", label: "Nome do acessorio", required: true },
      { name: "brand", label: "Marca", type: "select", optionGroup: "Marcas de Acessorios" },
      { name: "category", label: "Categoria", type: "select", optionGroup: "Categorias de Acessorios" },
      { name: "color", label: "Cor", type: "select", optionGroup: "Cores" },
      { name: "size", label: "Tamanho", type: "select", optionGroup: "Tamanhos" },
      { name: "stock", label: "Estoque", type: "number", defaultValue: 0 },
      { name: "minStock", label: "Estoque minimo", type: "number", defaultValue: 1 },
      { name: "price", label: "Preco", type: "currency" },
      { name: "cost", label: "Custo", type: "currency" },
      { name: "status", label: "Status", type: "select", optionGroup: "Status Catalogo", options: statusOptions, defaultValue: "ativo" },
      { name: "description", label: "Descricao", type: "textarea", full: true, maxLength: 800 },
    ],
  },
  clients: {
    title: "Clientes",
    description: "Gestao do parque de maquinas, contratos e informacoes operacionais.",
    actionLabel: "Novo Cliente",
    collection: "clients",
    layout: "table",
    formTitle: "Cadastro de Cliente",
    formDescription: "Dados de contato, contrato e maquina vinculada.",
    columns: [
      { key: "name", label: "Cliente" },
      { key: "contact", label: "Contato" },
      { key: "contractType", label: "Contrato" },
      { key: "machineId", label: "Maquina", source: "machines" },
      { key: "contractValue", label: "Valor", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { name: "name", label: "Nome / empresa", required: true },
      { name: "contact", label: "Pessoa de contato" },
      { name: "phone", label: "Telefone" },
      { name: "email", label: "Email" },
      { name: "contractType", label: "Tipo de contrato", type: "select", optionGroup: "Tipos de Contrato", options: [{ label: "Aluguel", value: "Aluguel" }, { label: "Venda", value: "Venda" }, { label: "Comodato", value: "Comodato" }, { label: "Comprador de Insumos", value: "Comprador de Insumos" }] },
      { name: "machineId", label: "Maquina vinculada", source: "machines" },
      { name: "contractValue", label: "Valor contrato", type: "currency" },
      { name: "status", label: "Status", type: "select", optionGroup: "Status Cliente", options: [{ label: "Concluido", value: "concluido" }, { label: "Cancelado", value: "cancelado" }, { label: "Quebra", value: "quebra" }], defaultValue: "concluido" },
      { name: "startDate", label: "Inicio contrato", type: "date" },
      { name: "address", label: "Endereco", type: "textarea", full: true },
    ],
  },
  checklists: {
    title: "Checklists",
    description: "Gerencie ordens de servico e instalacoes.",
    actionLabel: "Novo Checklist",
    collection: "checklists",
    layout: "table",
    formTitle: "Novo Checklist",
    formDescription: "Preencha os dados principais da ordem de servico.",
    validate: validateChecklistPayload,
    columns: [
      { key: "code", label: "N." },
      { key: "clientId", label: "Cliente", source: "clients" },
      { key: "machineId", label: "Maquina", source: "machines" },
      { key: "technician", label: "Tecnico" },
      { key: "date", label: "Data" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { name: "code", label: "Numero", required: true, placeholder: "#1043" },
      { name: "clientId", label: "Cliente", source: "clients", required: true },
      { name: "machineId", label: "Maquina", source: "machines", required: true },
      { name: "serviceType", label: "Tipo de servico", type: "select", optionGroup: "Tipos de Servico", options: [{ label: "Instalacao", value: "Instalacao" }, { label: "Retirada", value: "Retirada" }, { label: "Preventiva", value: "Preventiva" }, { label: "Manutencao", value: "Manutencao" }] },
      { name: "technician", label: "Tecnico responsavel", type: "select", optionGroup: "Tecnicos" },
      { name: "date", label: "Data", type: "date" },
      { name: "status", label: "Status", type: "select", optionGroup: "Status Checklist", options: checklistStatusOptions, defaultValue: "rascunho" },
      { name: "quantity", label: "Qtd maquinas", type: "number", defaultValue: 1 },
      { name: "outletAmperage", label: "Tomada do local (A)", type: "number", defaultValue: 10 },
      { name: "waterOk", label: "Rede hidrica ok", type: "select", optionGroup: "Rede Hidrica", options: [{ label: "Sim", value: "Sim" }, { label: "Nao", value: "Nao" }] },
      { name: "value", label: "Valor total", type: "currency" },
      { name: "notes", label: "Observacoes", type: "textarea", full: true, maxLength: 500 },
    ],
    extraActions: [
      {
        id: "details",
        label: "Detalhes",
        icon: "fileText",
        type: "detail",
      },
    ],
    detail: {
      title: (checklist) => `Checklist ${checklist?.code || ""}`,
      description: "Hub de leitura detalhada da ordem de servico.",
      fields: [
        { key: "code", label: "Numero" },
        { key: "status", label: "Status", type: "status" },
        { key: "clientId", label: "Cliente", source: "clients" },
        { key: "machineId", label: "Maquina", source: "machines" },
        { key: "serviceType", label: "Servico" },
        { key: "technician", label: "Tecnico" },
        { key: "date", label: "Data" },
        { key: "quantity", label: "Quantidade" },
        { key: "outletAmperage", label: "Tomada local" },
        { key: "waterOk", label: "Rede hidrica" },
        { key: "value", label: "Valor total", type: "currency" },
        { key: "notes", label: "Observacoes", full: true },
        {
          key: "compatibility",
          label: "Leitura de compatibilidade",
          full: true,
          render: (record, snapshot) => {
            const machine = snapshot.machines.find((item) => item.id === record.machineId);
            if (!machine) {
              return "-";
            }

            const amperageOk = Number(record.outletAmperage || 0) >= Number(machine.amperage || 0);
            const waterOk = machine.hydraulic !== "Sim" || record.waterOk === "Sim";
            return amperageOk && waterOk
              ? "Estrutura compativel com os requisitos da maquina."
              : "Falsa equivalencia detectada: revisar eletrica/hidrica antes de finalizar.";
          },
        },
      ],
    },
  },
  proposals: {
    title: "Portfolios e Fichas",
    description: "Gerenciamento de propostas, negociacoes com clientes e documentos operacionais.",
    actionLabel: "Nova Proposta",
    collection: "proposals",
    layout: "table",
    formTitle: "Editor de Proposta",
    formDescription: "Proposta comercial com preview de documento e integracao ao financeiro.",
    livePreviewDocumentType: "proposal",
    columns: [
      { key: "clientId", label: "Cliente", source: "clients" },
      { key: "machineId", label: "Maquina", source: "machines" },
      { key: "modality", label: "Modalidade" },
      { key: "totalValue", label: "Valor", type: "currency" },
      { key: "createdDate", label: "Criacao" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { name: "clientId", label: "Cliente", source: "clients", required: true },
      { name: "machineId", label: "Maquina", source: "machines", required: true },
      { name: "modality", label: "Modalidade", type: "select", optionGroup: "Modalidades Comerciais", options: [{ label: "Venda", value: "Venda" }, { label: "Aluguel", value: "Aluguel" }, { label: "Comodato", value: "Comodato" }] },
      { name: "status", label: "Status", type: "select", optionGroup: "Status Proposta", options: proposalStatusOptions, defaultValue: "rascunho" },
      { name: "totalValue", label: "Valor final", type: "currency" },
      { name: "createdDate", label: "Data", type: "date" },
      { name: "notes", label: "Observacoes", type: "textarea", full: true },
    ],
    extraActions: [
      {
        id: "proposalPreview",
        label: "Preview",
        icon: "fileText",
        type: "document",
        documentType: "proposal",
      },
    ],
  },
  serviceSheets: {
    title: "Fichas de Instalacao e Retirada",
    description: "Documentos operacionais vinculados a clientes, maquinas e checklists.",
    actionLabel: "Nova Ficha",
    collection: "serviceSheets",
    layout: "table",
    formTitle: "Gerador de Ficha",
    formDescription: "Ficha operacional com assinatura, preview e download de documento.",
    livePreviewDocumentType: "serviceSheet",
    columns: [
      { key: "sheetType", label: "Tipo" },
      { key: "clientId", label: "Cliente", source: "clients" },
      { key: "machineId", label: "Maquina", source: "machines" },
      { key: "checklistId", label: "Checklist", source: "checklists", sourceLabel: "code" },
      { key: "date", label: "Data" },
      { key: "status", label: "Status", type: "status" },
    ],
    fields: [
      { name: "sheetType", label: "Tipo de ficha", type: "select", optionGroup: "Tipos de Ficha", options: [{ label: "Instalacao", value: "Instalacao" }, { label: "Retirada", value: "Retirada" }] },
      { name: "clientId", label: "Cliente", source: "clients", required: true },
      { name: "machineId", label: "Maquina", source: "machines", required: true },
      { name: "checklistId", label: "Checklist vinculado", source: "checklists", sourceLabel: "code" },
      { name: "date", label: "Data", type: "date" },
      { name: "time", label: "Horario" },
      { name: "status", label: "Status", type: "select", optionGroup: "Status Ficha", options: [{ label: "Rascunho", value: "rascunho" }, { label: "Assinado", value: "assinado" }, { label: "Cancelado", value: "cancelado" }], defaultValue: "rascunho" },
      { name: "technician", label: "Tecnico", type: "select", optionGroup: "Tecnicos" },
      { name: "serviceMode", label: "Meio", type: "select", optionGroup: "Meio de Atendimento", options: [{ label: "Hidrica", value: "Hidrica" }, { label: "Galao", value: "Galao" }] },
      { name: "rentalValue", label: "Valor locacao", type: "currency" },
      { name: "chargeType", label: "Tipo cobranca", type: "select", optionGroup: "Tipos de Cobranca" },
      { name: "machineReading", label: "Leitura maquina" },
      { name: "technicalTests", label: "Checklist tecnico", type: "textarea", full: true },
      { name: "products", label: "Produtos / insumos", type: "textarea", full: true },
      { name: "notes", label: "Observacoes", type: "textarea", full: true },
    ],
    extraActions: [
      {
        id: "sheetPreview",
        label: "Preview",
        icon: "fileText",
        type: "document",
        documentType: "serviceSheet",
      },
    ],
  },
  sales: {
    title: "Vendas Rapidas",
    description: "Registro de vendas avulsas, saida de insumos e faturamento direto.",
    actionLabel: "Nova Venda",
    collection: "sales",
    layout: "table",
    formTitle: "Nova Venda",
    formDescription: "Ao salvar, o estoque virtual do item vendido e baixado automaticamente.",
    columns: [
      { key: "date", label: "Data" },
      { key: "clientId", label: "Cliente", source: "clients" },
      {
        key: "productId",
        label: "Produto",
        render: (record, snapshot) => snapshot[record.productCollection]?.find((item) => item.id === record.productId)?.name || "-",
      },
      { key: "quantity", label: "Qtd" },
      { key: "totalValue", label: "Valor", type: "currency" },
      { key: "paymentStatus", label: "Status", type: "status" },
    ],
    fields: [
      { name: "date", label: "Data", type: "date", required: true },
      { name: "clientId", label: "Cliente", source: "clients", required: true },
      { name: "inventoryItem", label: "Produto", type: "inventoryItem", required: true },
      { name: "quantity", label: "Quantidade", type: "number", defaultValue: 1 },
      { name: "unitValue", label: "Valor unitario", type: "currency" },
      { name: "paymentStatus", label: "Pagamento", type: "select", optionGroup: "Status Pagamento", options: paymentStatusOptions, defaultValue: "pendente" },
      { name: "generateCharge", label: "Lancar no contas a receber", type: "checkbox", defaultValue: false },
    ],
  },
  labels: {
    title: "Etiquetas",
    description: "Repositorio de arquivos externos de etiquetas, com preview, download e impressao.",
    actionLabel: "Enviar Arquivo",
    collection: "labels",
  },
  options: {
    title: "Adicionar Opcoes",
    description: "Gerenciamento de listas, categorias, parametros tecnicos e itens de checklist.",
    actionLabel: "Adicionar",
    collection: "options",
    layout: "table",
    formTitle: "Nova Opcao",
    formDescription: "Parametro usado por dropdowns e cadastros do sistema.",
    columns: [
      { key: "group", label: "Grupo" },
      { key: "name", label: "Nome" },
      { key: "value", label: "Valor" },
    ],
    fields: [
      { name: "group", label: "Grupo", type: "select", options: OPTION_GROUP_CHOICES, required: true },
      { name: "name", label: "Nome", required: true },
      { name: "value", label: "Valor", required: true },
    ],
  },
};
