import {
  Archive,
  BadgeDollarSign,
  BarChart3,
  Bell,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Calculator,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleUserRound,
  Coffee,
  Cog,
  Database,
  Download,
  FileClock,
  FileText,
  Gauge,
  History,
  Home,
  LayoutGrid,
  LogOut,
  Menu,
  PackagePlus,
  Pencil,
  Plus,
  ReceiptText,
  RotateCcw,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Tags,
  Trash2,
  UserPlus,
  Users,
  Wrench,
  X,
} from "lucide-react";

const ICONS = {
  archive: Archive,
  bell: Bell,
  boxes: Boxes,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calculator: Calculator,
  checkSquare: CheckSquare,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  coffee: Coffee,
  cog: Cog,
  dashboard: BarChart3,
  database: Database,
  download: Download,
  fileClock: FileClock,
  fileText: FileText,
  gauge: Gauge,
  history: History,
  home: Home,
  layoutGrid: LayoutGrid,
  logOut: LogOut,
  menu: Menu,
  money: BadgeDollarSign,
  packagePlus: PackagePlus,
  pencil: Pencil,
  plus: Plus,
  receipt: ReceiptText,
  refresh: RotateCcw,
  search: Search,
  settings: Settings,
  shield: Shield,
  shoppingCart: ShoppingCart,
  tags: Tags,
  trash: Trash2,
  user: CircleUserRound,
  userPlus: UserPlus,
  users: Users,
  wrench: Wrench,
  x: X,
};

export default function AppIcon({ name, size = 18, className = "" }) {
  const Icon = ICONS[name] || LayoutGrid;

  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={2} />;
}
